//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.ExternalServices.ContosoInventoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternalServices.ContosoInventoryService.ContosoInventoryService")]
    public interface ContosoInventoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContosoInventoryService/InStock", ReplyAction="http://tempuri.org/ContosoInventoryService/InStockResponse")]
        bool InStock(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContosoInventoryServiceChannel : Infrastructure.ExternalServices.ContosoInventoryService.ContosoInventoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContosoInventoryServiceClient : System.ServiceModel.ClientBase<Infrastructure.ExternalServices.ContosoInventoryService.ContosoInventoryService>, Infrastructure.ExternalServices.ContosoInventoryService.ContosoInventoryService {
        
        public ContosoInventoryServiceClient() {
        }
        
        public ContosoInventoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContosoInventoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContosoInventoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContosoInventoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InStock(int productId) {
            return base.Channel.InStock(productId);
        }
    }
}
