//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.WebServices.OrderProcessorServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServices.OrderProcessorServices.IOrderProcessorService")]
    public interface IOrderProcessorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProcessorService/IsCreditCardValid", ReplyAction="http://tempuri.org/IOrderProcessorService/IsCreditCardValidResponse")]
        bool IsCreditCardValid(string creditCardNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderProcessorServiceChannel : Infrastructure.WebServices.OrderProcessorServices.IOrderProcessorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderProcessorServiceClient : System.ServiceModel.ClientBase<Infrastructure.WebServices.OrderProcessorServices.IOrderProcessorService>, Infrastructure.WebServices.OrderProcessorServices.IOrderProcessorService {
        
        public OrderProcessorServiceClient() {
        }
        
        public OrderProcessorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderProcessorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsCreditCardValid(string creditCardNumber) {
            return base.Channel.IsCreditCardValid(creditCardNumber);
        }
    }
}
