//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.ExternalServices.AcmeShippingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternalServices.AcmeShippingService.AcmeShippingService")]
    public interface AcmeShippingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcmeShippingService/Ship", ReplyAction="http://tempuri.org/AcmeShippingService/ShipResponse")]
        string Ship(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AcmeShippingServiceChannel : Infrastructure.ExternalServices.AcmeShippingService.AcmeShippingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcmeShippingServiceClient : System.ServiceModel.ClientBase<Infrastructure.ExternalServices.AcmeShippingService.AcmeShippingService>, Infrastructure.ExternalServices.AcmeShippingService.AcmeShippingService {
        
        public AcmeShippingServiceClient() {
        }
        
        public AcmeShippingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcmeShippingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcmeShippingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcmeShippingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ship(int productId) {
            return base.Channel.Ship(productId);
        }
    }
}
