//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Core.Domain;

namespace Infrastructure.WebServices.ShippingServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServices.ShippingServices.IShippingService")]
    public interface IShippingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/Ship", ReplyAction="http://tempuri.org/IShippingService/ShipResponse")]
        string Ship(Product product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShippingServiceChannel : Infrastructure.WebServices.ShippingServices.IShippingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingServiceClient : System.ServiceModel.ClientBase<Infrastructure.WebServices.ShippingServices.IShippingService>, Infrastructure.WebServices.ShippingServices.IShippingService {
        
        public ShippingServiceClient() {
        }
        
        public ShippingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ship(Product product) {
            return base.Channel.Ship(product);
        }
    }
}
